const { contextBridge, ipcRenderer } = require('electron')
const { version } = require('../package.json')

contextBridge.exposeInMainWorld('daemoncore', {
  platform: process.platform,
  version,
  display: Object.freeze({
    setZoom: factor => ipcRenderer.invoke('display:set-zoom', factor),
  }),
  range: Object.freeze({
    availability: () => ipcRenderer.invoke('range:availability'),
    status: () => ipcRenderer.invoke('range:status'),
    manifest: id => ipcRenderer.invoke('range:manifest', id),
    packIndex: () => ipcRenderer.invoke('range:pack-index'),
    verifyPack: id => ipcRenderer.invoke('range:verify-pack', id),
    diagnostics: () => ipcRenderer.invoke('range:diagnostics'),
    exportReceipt: () => ipcRenderer.invoke('range:export-receipt'),
    contract: id => ipcRenderer.invoke('range:contract', id),
    start: (id, options) => ipcRenderer.invoke('range:start', id, options),
    execute: (id, command) => ipcRenderer.invoke('range:execute', id, command),
    validate: (id, objectiveIndex, executionId) => ipcRenderer.invoke('range:validate', id, objectiveIndex, executionId),
    hint: id => ipcRenderer.invoke('range:hint', id),
    complete: id => ipcRenderer.invoke('range:complete', id),
    chaosStatus: () => ipcRenderer.invoke('range:chaos-status'),
    chaosStart: input => ipcRenderer.invoke('range:chaos-start', input),
    chaosAbort: () => ipcRenderer.invoke('range:chaos-abort'),
    stop: () => ipcRenderer.invoke('range:stop'),
  }),
  data: Object.freeze({
    snapshot: () => ipcRenderer.invoke('data:snapshot'),
    onboard: handle => ipcRenderer.invoke('data:onboard', handle),
    record: event => ipcRenderer.invoke('data:record', event),
    updateSettings: settings => ipcRenderer.invoke('data:settings', settings),
    updateMissionOS: input => ipcRenderer.invoke('data:mission-os', input),
    reset: () => ipcRenderer.invoke('data:reset'),
    export: () => ipcRenderer.invoke('data:export'),
  }),
  license: Object.freeze({
    snapshot: () => ipcRenderer.invoke('license:snapshot'),
    activate: input => ipcRenderer.invoke('license:activate', input),
    validate: () => ipcRenderer.invoke('license:validate'),
    deactivate: () => ipcRenderer.invoke('license:deactivate'),
    checkout: () => ipcRenderer.invoke('license:checkout'),
  }),
  fieldops: Object.freeze({
    snapshot: () => ipcRenderer.invoke('fieldops:snapshot'),
    identity: () => ipcRenderer.invoke('fieldops:identity'),
    enrollIdentity: input => ipcRenderer.invoke('fieldops:identity-enroll', input),
    create: input => ipcRenderer.invoke('fieldops:create', input),
    run: input => ipcRenderer.invoke('fieldops:run', input),
    startCampaign: input => ipcRenderer.invoke('fieldops:campaign-start', input),
    pauseCampaign: id => ipcRenderer.invoke('fieldops:campaign-pause', id),
    resumeCampaign: id => ipcRenderer.invoke('fieldops:campaign-resume', id),
    cancelCampaign: id => ipcRenderer.invoke('fieldops:campaign-cancel', id),
    createFinding: input => ipcRenderer.invoke('fieldops:finding-create', input),
    updateFinding: (id, input) => ipcRenderer.invoke('fieldops:finding-update', { id, input }),
    retestFinding: (id, input) => ipcRenderer.invoke('fieldops:finding-retest', { id, input }),
    startChaos: input => ipcRenderer.invoke('fieldops:chaos-start', input),
    abortChaos: id => ipcRenderer.invoke('fieldops:chaos-abort', id),
    close: id => ipcRenderer.invoke('fieldops:close', id),
    export: id => ipcRenderer.invoke('fieldops:export', id),
    report: id => ipcRenderer.invoke('fieldops:report', id),
  }),
})
