[libdefaults]
 default_realm = DAEMONCORE.LAB
 dns_lookup_realm = false
 dns_lookup_kdc = true
 rdns = false
 forwardable = true
[realms]
 DAEMONCORE.LAB = { kdc = dc01.daemoncore.lab admin_server = dc01.daemoncore.lab }
[domain_realm]
 .daemoncore.lab = DAEMONCORE.LAB
 daemoncore.lab = DAEMONCORE.LAB
