import {useState} from 'react'
import {ArrowRight,Check,Clock3,Factory,Network,ShieldCheck,Terminal,Zap} from 'lucide-react'
import {enterpriseLabCatalog} from './enterprise-labs.js'

export function EnterpriseForgePage({profile,onLaunch}){
  const [filter,setFilter]=useState('ALL'),completed=profile.completedEnterpriseLabs||[],categories=['ALL',...new Set(enterpriseLabCatalog.map(lab=>lab.category))]
  const shown=filter==='ALL'?enterpriseLabCatalog:enterpriseLabCatalog.filter(lab=>lab.category===filter),progress=Math.round(completed.length/enterpriseLabCatalog.length*100)
  return <div className="page web-forge-page enterprise-forge-page"><section className="forge-hero enterprise-hero"><div className="forge-grid"/><div><span className="section-code"><i/> ENTERPRISE FORGE // MULTI-DOMAIN RANGE</span><h2>Read the control plane.<br/><em>Break the path.</em></h2><p>Forty-eight evidence cases across enterprise identity, cloud, detection, Linux hosts, Kubernetes, and software supply chain. Each case requires a positive control, an effective-decision calculation, and a bounded closure statement.</p><div className="forge-pills"><span><ShieldCheck/> EGRESS BLOCKED</span><span><Terminal/> ROOT CONSOLE</span><span><Network/> 06 DOMAINS</span></div></div><div className="forge-meter"><div><strong>{progress}</strong><span>% FORGED</span></div><small>{completed.length} / {enterpriseLabCatalog.length} CASES SEALED</small></div></section>
    <section className="forge-stats"><div><span>LIVE CASES</span><strong>48</strong><small>SYNTHETIC ENTERPRISE EVIDENCE</small></div><div><span>SPECIALIST DOMAINS</span><strong>06</strong><small>IDENTITY TO SUPPLY CHAIN</small></div><div><span>OPERATION MODEL</span><strong>CALCULATED</strong><small>BASELINE // COMPARISON</small></div><div><span>MAX RANGE XP</span><strong>{enterpriseLabCatalog.reduce((sum,lab)=>sum+lab.xp,0).toLocaleString()}</strong><small>LIVE EVIDENCE ONLY</small></div></section>
    <div className="forge-filter">{categories.map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item}</button>)}</div>
    <div className="forge-labs">{shown.map((lab,index)=>{const done=completed.includes(lab.id);return <article key={lab.id} className={done?'complete':''}><header><span>{lab.category} // {String(index+1).padStart(2,'0')}</span><em>{lab.difficulty}</em></header><div className="forge-lab-icon">{done?<Check/>:<Factory/>}</div><h3>{lab.title}</h3><p>{lab.brief}</p><footer><span><Clock3/>{lab.minutes} MIN</span><span><Zap/>{lab.xp} XP</span><button onClick={()=>onLaunch(lab)}>{done?'REPLAY':'ENTER'} <ArrowRight/></button></footer></article>})}</div></div>
}
