import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowRight, Check, ClipboardCheck, FileSearch, Fingerprint, Plus, RotateCcw, Server, ShieldCheck, X } from 'lucide-react'

const levels=['informational','low','medium','high','critical']
const statuses=['open','accepted-risk','resolved','false-positive']
const stamp=value=>new Date(value).toLocaleString()

function FindingForm({ engagement, captures, initialCaptureId, onCreate, onClose }) {
  const [form,setForm]=useState({captureId:initialCaptureId||captures[0]?.id||'',title:'',severity:'medium',description:'',impact:'',remediation:''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const update=(key,value)=>setForm(current=>({...current,[key]:value}))
  const selected=captures.find(item=>item.id===form.captureId)
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{await onCreate({...form,engagementId:engagement.id});onClose()}catch(caught){setError(caught.message)}finally{setBusy(false)}}
  return <div className="modal-backdrop"><form className="finding-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}><X/></button><span>FINDING WORKBENCH // EVIDENCE REQUIRED</span><h2>Promote a verified observation.</h2><p>Every finding remains linked to the original immutable capture and its SHA-256 digest.</p><div className="finding-fields"><label className="wide">SEALED EVIDENCE<select value={form.captureId} onChange={event=>update('captureId',event.target.value)}>{captures.map(item=><option value={item.id} key={item.id}>{item.type.toUpperCase()} · {item.target}{item.port?`:${item.port}`:''} · {stamp(item.at)}</option>)}</select></label><label className="wide">FINDING TITLE<input value={form.title} maxLength={140} onChange={event=>update('title',event.target.value)} placeholder="TLS certificate chain fails independent validation"/></label><label>SEVERITY<select value={form.severity} onChange={event=>update('severity',event.target.value)}>{levels.map(level=><option key={level}>{level}</option>)}</select></label><label>TARGET<input value={selected?.target||''} disabled/></label><label className="wide">OBSERVATION<textarea value={form.description} onChange={event=>update('description',event.target.value)} placeholder="State exactly what was observed, how the control behaved, and what the evidence proves."/></label><label className="wide">IMPACT<textarea value={form.impact} onChange={event=>update('impact',event.target.value)} placeholder="Describe the bounded technical and business consequence without overstating reach."/></label><label className="wide">REMEDIATION<textarea value={form.remediation} onChange={event=>update('remediation',event.target.value)} placeholder="Give the owner a specific control change and a measurable closure condition."/></label></div>{error&&<div className="field-error">BLOCKED // {error}</div>}<button className="finding-submit" disabled={busy||!form.captureId}>{busy?'SEALING FINDING':'Seal finding'} <ArrowRight/></button></form></div>
}

function FindingCard({ finding, captures, onUpdate, onRetest }) {
  const available=captures.filter(item=>!finding.evidenceIds.includes(item.id)),[captureId,setCaptureId]=useState(available[0]?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const act=async action=>{setBusy(true);setError('');try{await action()}catch(caught){setError(caught.message)}finally{setBusy(false)}}
  return <article className={`finding-card severity-${finding.severity}`}><header><div><span>{finding.severity.toUpperCase()} // {finding.target}</span><h3>{finding.title}</h3></div><select disabled={busy} value={finding.status} onChange={event=>act(()=>onUpdate(finding.id,{status:event.target.value}))}>{statuses.map(status=><option value={status} key={status}>{status.replace('-',' ').toUpperCase()}</option>)}</select></header><div className="finding-copy"><section><span>OBSERVATION</span><p>{finding.description}</p></section><section><span>IMPACT</span><p>{finding.impact||'Not recorded.'}</p></section><section><span>REMEDIATION</span><p>{finding.remediation||'Not recorded.'}</p></section></div><footer><div><Fingerprint/><span>{finding.evidenceIds.length} SEALED CAPTURE{finding.evidenceIds.length===1?'':'S'}</span><small>{finding.retests.length} RETEST{finding.retests.length===1?'':'S'} // UPDATED {stamp(finding.updatedAt)}</small></div>{available.length>0&&<div className="retest-controls"><select value={captureId} onChange={event=>setCaptureId(event.target.value)}>{available.map(item=><option value={item.id} key={item.id}>{item.type.toUpperCase()} · {stamp(item.at)}</option>)}</select><button disabled={busy||!captureId} onClick={()=>act(()=>onRetest(finding.id,{captureId,verdict:'still-present'}))}><RotateCcw/> Still present</button><button disabled={busy||!captureId} onClick={()=>act(()=>onRetest(finding.id,{captureId,verdict:'fixed'}))}><Check/> Verified fixed</button></div>}</footer>{error&&<div className="field-error">{error}</div>}</article>
}

export function EvidenceWorkspace({ engagement, data, onPromote }) {
  const captures=useMemo(()=>data.captures.filter(item=>item.engagementId===engagement.id),[data.captures,engagement.id])
  const assets=engagement.targets.map(target=>{const items=captures.filter(item=>item.target===target),ports=[...new Set(items.flatMap(item=>item.type==='ports'?(item.result?.observations||[]).filter(port=>port.state==='open').map(port=>port.port):item.type==='surface'?(item.result?.summary?.openPorts||[]):item.port?[item.port]:[]))];return{target,items,ports,last:items[0]?.at,baselined:items.some(item=>item.type==='surface')}})
  return <div className="field-workspace"><section className="asset-board"><header><Server/><div><span>ASSET INTELLIGENCE</span><strong>{assets.length} AUTHORIZED ASSETS // {captures.length} SEALED CAPTURES</strong></div></header><div className="asset-grid">{assets.map(asset=><article key={asset.target}><i className={asset.items.length?'observed':''}/><span>{asset.baselined?'BASELINED':asset.items.length?'OBSERVED':'PENDING'}</span><h3>{asset.target}</h3><p>{asset.ports.length?`Observed ports // ${asset.ports.join(', ')}`:'No service evidence captured yet'}</p><small>{asset.last?`LAST SIGNAL ${stamp(asset.last)}`:'AWAITING FIRST DIAGNOSTIC'}</small></article>)}</div></section><section className={`capture-vault ${data.captureIntegrity===false?'integrity-failed':''}`}><header><FileSearch/><span>EVIDENCE VAULT</span><strong>{data.captureIntegrity===false?'INTEGRITY FAILED':'SHA-256 VERIFIED'}</strong></header>{captures.length?captures.map(item=><div className="capture-row" key={item.id}><ShieldCheck/><div><span>{item.type.toUpperCase()} // {item.target}{item.port?`:${item.port}`:''}{item.path||''}</span><strong>{item.digest}</strong><small>{stamp(item.at)} // {item.durationMs} MS</small></div><button disabled={data.captureIntegrity===false} onClick={()=>onPromote(item.id)}><Plus/> Create finding</button></div>):<div className="workspace-empty"><FileSearch/><strong>No evidence captured.</strong><span>Run a scoped diagnostic to begin the asset record.</span></div>}</section></div>
}

export function FindingsWorkspace({ engagement, data, initialCaptureId, onClearInitial, onCreate, onUpdate, onRetest }) {
  const captures=useMemo(()=>data.captures.filter(item=>item.engagementId===engagement.id),[data.captures,engagement.id]),findings=useMemo(()=>data.findings.filter(item=>item.engagementId===engagement.id),[data.findings,engagement.id])
  const [open,setOpen]=useState(Boolean(initialCaptureId))
  const close=()=>{setOpen(false);onClearInitial()}
  return <div className="field-workspace"><section className="findings-head"><div><ClipboardCheck/><span>FINDINGS REGISTER</span><strong>{findings.filter(item=>item.status==='open').length} OPEN // {findings.length} TOTAL</strong></div><button disabled={!captures.length} onClick={()=>setOpen(true)}><Plus/> New finding</button></section>{findings.length?<div className="findings-list">{findings.map(finding=><FindingCard key={finding.id} finding={finding} captures={captures} onUpdate={onUpdate} onRetest={onRetest}/>)}</div>:<div className="workspace-empty findings-empty"><AlertTriangle/><strong>No reviewed findings.</strong><span>Promote sealed diagnostic evidence when an observation meets the reporting threshold.</span><button disabled={!captures.length} onClick={()=>setOpen(true)}>Open finding workbench</button></div>}{open&&<FindingForm key={initialCaptureId||'manual'} engagement={engagement} captures={captures} initialCaptureId={initialCaptureId} onCreate={onCreate} onClose={close}/>}</div>
}
