import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, CreditCard, Database, Download, ExternalLink, Hexagon, KeyRound, LockKeyhole, RefreshCw, RotateCcw, ShieldCheck, SlidersHorizontal, Unplug, X } from 'lucide-react'

export function LoadingScreen() {
  return <div className="boot-screen"><div className="boot-logo"><Hexagon size={68}/><i/></div><span>DAEMONCORE ACADEMY</span><strong>Loading operator record…</strong></div>
}

export function Onboarding({ onComplete }) {
  const [handle, setHandle] = useState('')
  const [accepted, setAccepted] = useState(false)
  const [error, setError] = useState('')
  const submit = async event => {
    event.preventDefault(); setError('')
    try { await onComplete(handle) } catch (caught) { setError(caught.message) }
  }
  return <div className="onboarding"><div className="onboarding-grid"/><main><div className="onboard-brand"><Hexagon size={42}/><i/></div><span>FIRST BOOT // OPERATOR REGISTRATION</span><h1>Build the record.<br/><em>Earn everything else.</em></h1><p>DaemonCore starts clean. No fake rank. No seeded XP. Your record is stored locally and only changes when you complete real work.</p><form onSubmit={submit}><label>OPERATOR HANDLE<input autoFocus value={handle} maxLength={20} onChange={e=>setHandle(e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,''))} placeholder="NIGHTSHIFT"/><small>2–20 letters, numbers, underscores, or dashes</small></label><label className="roe-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>{accepted?<Check size={13}/>:null}</span><p>I will use DaemonCore only on systems I own or am explicitly authorized to test.</p></label>{error&&<div className="onboard-error">{error}</div>}<button disabled={!accepted||handle.length<2}>Initialize operator record <ArrowRight size={16}/></button></form><footer><ShieldCheck size={15}/> LOCAL-FIRST // NO ACCOUNT REQUIRED // EXPORT ANYTIME</footer></main></div>
}

export function LicensePanel({ license, onActivate, onValidate, onDeactivate, onCheckout, gate = false }) {
  const [key,setKey]=useState(''),[email,setEmail]=useState(''),[device,setDevice]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmDeactivate,setConfirmDeactivate]=useState(false)
  const run=async action=>{setBusy(true);setError('');try{await action()}catch(caught){setError(caught.message)}finally{setBusy(false)}}
  const body=!license.configured?<div className="license-unconfigured"><LockKeyhole/><div><span>BUILD CONFIGURATION REQUIRED</span><h3>Connect the Lemon Squeezy product.</h3><p>Set the public store, product, and variant IDs in <code>electron/license-policy.json</code> before producing the commercial installer. No API secret belongs in the app.</p></div></div>:license.licensed?<div className="license-active"><div className="license-seal"><ShieldCheck/><i/></div><div className="license-identity"><span>ENTITLEMENT VERIFIED</span><h3>{license.tierLabel}</h3><p>{license.productName} // {license.variantName||'DEFAULT VARIANT'}</p><div><em>{license.maskedKey}</em><em>{license.customerEmail}</em><em>DEVICE // {license.instanceName}</em></div></div><div className="license-state"><span className={license.status}>{license.status.toUpperCase()}</span><small>VALIDATED</small><strong>{license.validatedAt?new Date(license.validatedAt).toLocaleDateString():'—'}</strong>{license.status==='grace'&&<p>{license.graceRemainingDays} offline days remain</p>}</div><div className="license-actions"><button disabled={busy} onClick={()=>run(onValidate)}><RefreshCw/> Check now</button><button className="danger" onClick={()=>setConfirmDeactivate(true)}><Unplug/> Deactivate</button></div></div>:<form className="license-form" onSubmit={event=>{event.preventDefault();run(()=>onActivate({licenseKey:key,email,instanceName:device}))}}><div><KeyRound/><span>ACTIVATE DAEMONCORE</span><h3>Turn this install into your machine.</h3><p>Use the key from your Lemon Squeezy receipt. It is encrypted for this Windows account and never written to the operator record.</p></div><label>LICENSE KEY<input value={key} onChange={event=>setKey(event.target.value)} placeholder="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" autoComplete="off"/></label><label>CHECKOUT EMAIL <small>OPTIONAL VERIFICATION</small><input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="operator@example.com"/></label><label>DEVICE NAME<input value={device} maxLength={80} onChange={event=>setDevice(event.target.value)} placeholder="RED-RIG-01"/></label><button disabled={busy||key.trim().length<8}>{busy?'CONTACTING LICENSE SERVICE':'Activate this device'} <ArrowRight/></button>{license.checkoutUrl&&<button type="button" className="buy-license" onClick={onCheckout}><CreditCard/> Buy a license <ExternalLink/></button>}</form>
  return <section className={`license-panel ${gate?'gate':''}`}><header><div><span>LEMON SQUEEZY LICENSING</span><h2>{gate?'License required':'License & entitlement'}</h2></div><strong>SECURE STORAGE // OFFLINE GRACE</strong></header>{body}{error&&<p className="license-error">{error}</p>}{confirmDeactivate&&<div className="modal-backdrop"><div className="reset-modal"><button className="modal-close" onClick={()=>setConfirmDeactivate(false)}><X/></button><Unplug/><span>DEVICE DEACTIVATION</span><h2>Release this activation?</h2><p>The operator record stays on this machine. Premium access ends here and the activation slot returns to the license.</p><button onClick={()=>run(async()=>{await onDeactivate();setConfirmDeactivate(false)})}>Deactivate this device</button></div></div>}</section>
}

export function LicenseGate(props) {
  return <div className="license-gate"><div className="onboarding-grid"/><main><div className="onboard-brand"><Hexagon size={42}/><i/></div><span>COMMERCIAL BUILD // ENTITLEMENT GATE</span><h1>Premium access.<br/><em>Properly licensed.</em></h1><p>Activate this Windows installation to unlock DaemonCore Academy.</p><LicensePanel {...props} gate/></main></div>
}

export function SettingsPage({ data, license, onUpdate, onExport, onReset, onActivate, onValidate, onDeactivate, onCheckout }) {
  const [resetOpen,setResetOpen]=useState(false),[confirmation,setConfirmation]=useState(''),[message,setMessage]=useState('')
  const settings=data.settings
  const exportData=async()=>{const result=await onExport();setMessage(result?.canceled?'Export canceled':result?.filePath?`Saved to ${result.filePath}`:'Record downloaded')}
  return <div className="page settings-page"><div className="page-intro"><div><span className="section-code">LOCAL CONTROL PLANE</span><h2>Settings &amp;<br/><em>operator data.</em></h2></div><p>Your progress stays local. Licensing proves entitlement without mixing customer credentials into the training record.</p></div><LicensePanel license={license} onActivate={onActivate} onValidate={onValidate} onDeactivate={onDeactivate} onCheckout={onCheckout}/><section className="settings-block"><header><SlidersHorizontal/><div><span>INTERFACE</span><h3>Display preferences</h3></div></header><div className="scale-setting"><div><strong>Interface size</strong><small>Scales every screen, lesson, console, and control. Readable is the new default.</small></div><div>{[1,1.15,1.25,1.4].map(scale=><button key={scale} className={(Number(settings.uiScale)||1.25)===scale?'active':''} onClick={()=>onUpdate({...settings,uiScale:scale})}>{Math.round(scale*100)}%</button>)}</div></div><label><div><strong>Reduce motion</strong><small>Disable nonessential animation and orbit effects.</small></div><input type="checkbox" checked={settings.reduceMotion} onChange={e=>onUpdate({...settings,reduceMotion:e.target.checked})}/><i/></label><label><div><strong>Compact navigation</strong><small>Start the side rail in compact mode.</small></div><input type="checkbox" checked={settings.compactMode} onChange={e=>onUpdate({...settings,compactMode:e.target.checked})}/><i/></label></section><section className="settings-block"><header><Database/><div><span>OPERATOR RECORD</span><h3>Backup and recovery</h3></div></header><div className="data-action"><div><strong>Export everything</strong><small>Lessons, attempts, scores, achievements, settings, and timestamps.</small></div><button onClick={exportData}><Download size={15}/> Export JSON</button></div><div className="data-action danger"><div><strong>Reset Academy</strong><small>Deletes the local operator record and returns to first boot.</small></div><button onClick={()=>setResetOpen(true)}><RotateCcw size={15}/> Reset data</button></div>{message&&<p className="settings-message">{message}</p>}</section>{resetOpen&&<div className="modal-backdrop"><div className="reset-modal"><button className="modal-close" onClick={()=>setResetOpen(false)}><X size={17}/></button><LockKeyhole size={28}/><span>DESTRUCTIVE OPERATION</span><h2>Erase the operator record?</h2><p>This removes all local progress. Export first if you may want it later.</p><label>TYPE RESET TO CONFIRM<input value={confirmation} onChange={e=>setConfirmation(e.target.value.toUpperCase())}/></label><button disabled={confirmation!=='RESET'} onClick={onReset}>Erase local record</button></div></div>}</div>
}

export function ArticleReader({ article, onClose }) {
  return <div className="article-reader"><aside><button onClick={onClose}><ArrowLeft size={15}/> Intel library</button><div><span>{article.type}</span><h2>{article.title}</h2><p>{article.readMinutes} MIN READ</p></div></aside><main><header><span>DAEMONCORE FIELD INTELLIGENCE</span><button onClick={onClose}><X size={17}/></button></header><article><span>{article.type} // VERIFIED CONTENT</span><h1>{article.title}</h1><p className="article-summary">{article.summary}</p>{article.sections.map(([title,body],i)=><section key={title}><em>0{i+1}</em><div><h3>{title}</h3><p>{body}</p></div></section>)}<footer>END OF FIELD NOTE // RETURN TO THE OPERATION WITH A BETTER QUESTION.</footer></article></main></div>
}
