import { useEffect, useRef, useState } from 'react'
import { Activity, AlertTriangle, Box, Check, CircleStop, Gauge, Play, ShieldCheck, Trash2, Waves } from 'lucide-react'

const profiles={baseline:'STEADY BASELINE',ramp:'BREAKPOINT RAMP',spike:'SURGE EVENT',soak:'SATURATION SOAK'}
const running=new Set(['running','recovering'])

export function RangeChaosLab(){
  const api=window.daemoncore?.range
  const ownsRange=useRef(false)
  const [engine,setEngine]=useState(api?'checking':'preview'),[run,setRun]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [form,setForm]=useState({profile:'ramp',durationSeconds:20,requestsPerSecond:100,concurrency:25,p95LimitMs:1000,errorRateLimit:20})
  const active=running.has(run?.status)
  const update=(key,value)=>setForm(current=>({...current,[key]:value}))
  useEffect(()=>{if(!api)return;api.status().then(status=>setEngine(status.state)).catch(caught=>{setEngine('offline');setError(caught.message)})},[api])
  useEffect(()=>{if(!api||!active)return;const timer=setInterval(()=>api.chaosStatus().then(setRun).catch(caught=>setError(caught.message)),500);return()=>clearInterval(timer)},[active,api])
  useEffect(()=>()=>{if(ownsRange.current)api?.stop().catch(()=>{})},[api])
  const launch=async()=>{if(!api){setError('Install the Windows build and Docker Desktop to run the sealed worker.');return}setBusy(true);setError('');try{let status=await api.status();if(status.state!=='sealed'){setEngine('provisioning');status=await api.start('ghost-port');ownsRange.current=true}setEngine(status.state);setRun(await api.chaosStart(form))}catch(caught){setError(caught.message);setEngine('offline')}finally{setBusy(false)}}
  const abort=async()=>{setBusy(true);try{setRun(await api.chaosAbort())}catch(caught){setError(caught.message)}finally{setBusy(false)}}
  const destroy=async()=>{setBusy(true);try{await api.stop();ownsRange.current=false;setEngine('ready');setRun(null)}catch(caught){setError(caught.message)}finally{setBusy(false)}}
  const metrics=run?.metrics||{},recovery=run?.recovery||{},progress=run?.progress||0
  return <section className="range-chaos-lab">
    <header><div className="range-chaos-mark"><Waves/><i/></div><div><span>DAEMONCORE CHAOS ENGINE // SEALED POWER DOMAIN</span><h3>Black Box Breakpoint Lab</h3><p>High-intensity load, collapse detection, and recovery proof against a disposable target with zero network egress.</p></div><div className={`range-chaos-state ${active?'live':''}`}><i/><span>{engine.toUpperCase()}</span><strong>{active?run.phase?.toUpperCase():'WORKER STANDBY'}</strong></div></header>
    <div className="range-power-strip"><div><ShieldCheck/><span>BOUNDARY</span><strong>INTERNAL-ONLY</strong></div><div><Gauge/><span>MAX THROUGHPUT</span><strong>500 REQ/S</strong></div><div><Activity/><span>MAX CONCURRENCY</span><strong>100 WORKERS</strong></div><div><Box/><span>MAX BUDGET</span><strong>30,000 REQUESTS</strong></div></div>
    <div className="range-chaos-body"><div className="range-chaos-config"><div className="range-profile-grid">{Object.entries(profiles).map(([id,label])=><button key={id} className={form.profile===id?'active':''} disabled={active||busy} onClick={()=>update('profile',id)}><span>{label}</span><small>{id==='baseline'?'Known steady state':id==='ramp'?'Find the failure edge':id==='spike'?'Prove surge handling':'Expose accumulation'}</small></button>)}</div><div className="range-chaos-fields"><label>DURATION // SEC<input type="number" min="10" max="60" disabled={active} value={form.durationSeconds} onChange={event=>update('durationSeconds',Number(event.target.value))}/></label><label>CEILING // REQ/S<input type="number" min="10" max="500" disabled={active} value={form.requestsPerSecond} onChange={event=>update('requestsPerSecond',Number(event.target.value))}/></label><label>CONCURRENCY<input type="number" min="1" max="100" disabled={active} value={form.concurrency} onChange={event=>update('concurrency',Number(event.target.value))}/></label><label>P95 ABORT // MS<input type="number" min="100" max="10000" disabled={active} value={form.p95LimitMs} onChange={event=>update('p95LimitMs',Number(event.target.value))}/></label><label>ERROR ABORT // %<input type="number" min="1" max="80" disabled={active} value={form.errorRateLimit} onChange={event=>update('errorRateLimit',Number(event.target.value))}/></label></div><div className="range-chaos-safety"><span><Check/> INTERNAL DOCKER DNS</span><span><Check/> NO PUBLISHED PORTS</span><span><Check/> ZERO HOST MOUNTS</span><span><Check/> EGRESS DENIED</span></div>{error&&<div className="range-chaos-error"><AlertTriangle/>{error}</div>}<div className="range-chaos-actions"><small>DECLARED WORST CASE // {Math.min(30000,form.durationSeconds*form.requestsPerSecond).toLocaleString()} REQUESTS</small>{active?<button className="stop" disabled={busy} onClick={abort}><CircleStop/> Emergency stop</button>:<button disabled={busy} onClick={launch}><Play/> {busy?'PROVISIONING RANGE':'Provision and execute'}</button>}{engine==='sealed'&&!active&&<button className="destroy" disabled={busy} onClick={destroy}><Trash2/> Destroy range</button>}</div></div>
      <aside className="range-chaos-telemetry"><header><span>LIVE RANGE TELEMETRY</span><strong className={run?.status||'idle'}>{run?.status?.toUpperCase()||'NO RUN'}</strong></header><div className="range-signal"><i style={{'--progress':`${progress*3.6}deg`}}><strong>{progress}</strong><span>%</span></i></div><div className="range-readouts"><div><span>TOTAL REQUESTS</span><strong>{(metrics.requests||0).toLocaleString()}</strong></div><div><span>OBSERVED RPS</span><strong>{run?.requestsPerSecond||0}</strong></div><div><span>P95 LATENCY</span><strong>{metrics.p95Ms||0}<small> MS</small></strong></div><div><span>ERROR RATE</span><strong>{metrics.errorRate||0}<small>%</small></strong></div><div><span>RECOVERY P95</span><strong>{recovery.p95Ms||0}<small> MS</small></strong></div><div><span>RESILIENCE SCORE</span><strong>{run?.resilienceScore??'—'}</strong></div></div><p>{run?.outcome||'Provision the sealed target and worker to begin a live breakpoint experiment.'}</p></aside>
    </div>
  </section>
}
