import { useEffect, useRef, useState } from 'react'
import { Activity, ArrowLeft, ArrowRight, Braces, Check, Clock3, Crosshair, Flag, HardDrive, Hexagon, Play, ShieldCheck, Sparkles, Terminal, Zap } from 'lucide-react'
import { webLabCatalog } from './web-labs.js'

export function WebForgePage({ profile, onLaunch }) {
  const [filter,setFilter]=useState('ALL')
  const completed=profile.completedWebLabs||[], categories=['ALL',...new Set(webLabCatalog.map(lab=>lab.category))]
  const shown=filter==='ALL'?webLabCatalog:webLabCatalog.filter(lab=>lab.category===filter)
  const progress=Math.round(completed.length/webLabCatalog.length*100)
  return <div className="page web-forge-page">
    <section className="forge-hero"><div className="forge-grid"/><div><span className="section-code"><i/> WEB FORGE // LIVE SPECIALIST RANGE</span><h2>Interrogate trust.<br/><em>Prove the break.</em></h2><p>Twenty-two vulnerable applications and API conditions running inside one disposable, egress-blocked Docker range. Every operation requires a baseline, a controlled comparison, and an accepted evidence statement.</p><div className="forge-pills"><span><ShieldCheck/> INTERNAL NETWORK</span><span><Terminal/> ROOT CONSOLE</span><span><Crosshair/> 22 SCENARIOS</span></div></div><div className="forge-meter"><div><strong>{progress}</strong><span>% FORGED</span></div><small>{completed.length} / {webLabCatalog.length} CONDITIONS SEALED</small></div></section>
    <section className="forge-stats"><div><span>LIVE CONDITIONS</span><strong>22</strong><small>NO PLACEHOLDERS</small></div><div><span>DOMAIN COVERAGE</span><strong>{categories.length-1}</strong><small>BROWSER TO PROTOCOL</small></div><div><span>RANGE BOUNDARY</span><strong>SEALED</strong><small>HOST MOUNTS 0 // EGRESS 0</small></div><div><span>MAX RANGE XP</span><strong>{webLabCatalog.reduce((n,l)=>n+l.xp,0).toLocaleString()}</strong><small>EVIDENCE-BASED</small></div></section>
    <div className="forge-filter">{categories.map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item}</button>)}</div>
    <div className="forge-labs">{shown.map((lab,index)=>{const done=completed.includes(lab.id);return <article key={lab.id} className={done?'complete':''}><header><span>{lab.category} // {String(index+1).padStart(2,'0')}</span><em>{lab.difficulty}</em></header><div className="forge-lab-icon">{done?<Check/>:<Braces/>}</div><h3>{lab.title}</h3><p>{lab.brief}</p><footer><span><Clock3/>{lab.minutes} MIN</span><span><Zap/>{lab.xp} XP</span><button onClick={()=>onLaunch(lab)}>{done?'REPLAY':'ENTER'} <ArrowRight/></button></footer></article>})}</div>
  </div>
}

export function WebLabRunner({ lab, onExit, onComplete, rangeId='web-range', forgeName='Web Forge' }) {
  const api=window.daemoncore?.range
  const [engine,setEngine]=useState(api?'starting':'offline'),[error,setError]=useState(api?'':`${forgeName} requires the desktop build and a running Docker engine.`),[containment,setContainment]=useState(null)
  const [input,setInput]=useState(''),[history,setHistory]=useState([]),[done,setDone]=useState([]),[evidence,setEvidence]=useState([]),[busy,setBusy]=useState(false),[hints,setHints]=useState(0),[seconds,setSeconds]=useState(0),[report,setReport]=useState(false)
  const scrollRef=useRef(null)
  useEffect(()=>{let live=true;(async()=>{if(!api)return;try{const result=await api.start(rangeId);if(live){setContainment(result.containment);setEngine('live');setHistory([{kind:'system',text:`${forgeName.toUpperCase()} SEALED // ${result.containment.network} // EGRESS BLOCKED`}])}}catch(failure){if(live){setEngine('offline');setError(failure.message)}}})();return()=>{live=false;api?.stop().catch(()=>{})}},[api,forgeName,rangeId])
  useEffect(()=>{if(engine!=='live'||report)return;const timer=setInterval(()=>setSeconds(value=>value+1),1000);return()=>clearInterval(timer)},[engine,report])
  useEffect(()=>{if(scrollRef.current)scrollRef.current.scrollTop=scrollRef.current.scrollHeight},[history])
  useEffect(()=>{if(engine==='live'&&!busy&&!report)scrollRef.current?.parentElement?.querySelector('input')?.focus()},[engine,busy,report,history])
  const format=value=>`${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`
  const run=async command=>{const raw=(command||input).trim();if(!raw||busy||engine!=='live')return;setInput('');if(raw==='hint'){setHints(value=>value+1);setHistory(items=>[...items,{kind:'command',text:'hint'},{kind:'hint',text:lab.hint}]);return}setBusy(true);setHistory(items=>[...items,{kind:'command',text:raw}]);try{const result=await api.execute(rangeId,raw),output=`${result.stdout||''}${result.stderr||''}`.trim();setHistory(items=>[...items,{kind:result.exitCode===0?'output':'error',text:output||`Process exited ${result.exitCode}`}]);const step=lab.steps.findIndex(item=>item.command===raw);if(result.exitCode===0&&step>=0&&!done.includes(step)){setDone(items=>[...items,step]);setEvidence(items=>[...items,lab.steps[step].evidence])}if(result.exitCode===0&&(/FINDING ACCEPTED/.test(output)||/"accepted"\s*:\s*true/.test(output))){setDone([0,1,2,3]);setReport(true)}}catch(failure){setHistory(items=>[...items,{kind:'error',text:`RANGE ERROR // ${failure.message}`}])}finally{setBusy(false)}}
  const leave=async()=>{await api?.stop().catch(()=>{});onExit()}
  const score=Math.max(200,lab.xp-hints*75-Math.floor(seconds/60)*5)
  const finish=async()=>{await api?.stop().catch(()=>{});onComplete({type:'webLab',id:lab.id,title:lab.title,score,hints,seconds,minutes:lab.minutes})}
  if(engine==='starting')return <div className="forge-gate"><Hexagon/><span>WEB FORGE // RANGE ORCHESTRATOR</span><h1>Building the specialist range.</h1><p>Compiling the target, proving the internal network, checking host mounts, and denying internet egress before the console opens.</p><div><Activity/> CONTAINMENT PROOF IN PROGRESS</div><button onClick={leave}>Cancel launch</button></div>
  if(engine==='offline')return <div className="forge-gate offline"><HardDrive/><span>{forgeName.toUpperCase()} OFFLINE</span><h1>Docker isn’t ready.</h1><p>{error}</p><strong>No simulation credit is available. {forgeName} completion requires output from the live sealed target.</strong><button onClick={onExit}>Return to catalog</button></div>
  if(report)return <div className="forge-complete"><ShieldCheck/><span>FINDING ACCEPTED // RANGE EVIDENCE SEALED</span><h1>{lab.title}</h1><p>The live target accepted the precise condition. The range can now be destroyed and the attempt written to your operator record.</p><div><section><small>OPERATION SCORE</small><strong>{score}</strong></section><section><small>OBJECTIVES</small><strong>4 / 4</strong></section><section><small>GUIDANCE</small><strong>{hints}</strong></section><section><small>ELAPSED</small><strong>{format(seconds)}</strong></section></div><button onClick={finish}>Destroy range &amp; log result <ArrowRight/></button></div>
  return <div className="forge-runner"><header><button onClick={leave}><ArrowLeft/></button><Hexagon/><div><span>DAEMONCORE // WEB FORGE</span><strong>{lab.title}</strong></div><aside><span><i/> CONTAINMENT VERIFIED</span><span><Clock3/> {format(seconds)}</span><span>{containment?.network}</span><button onClick={leave}>DESTROY &amp; EXIT</button></aside></header><main><section className="forge-console"><div className="forge-console-bar"><span/><span/><span/><strong>ROOT@DC-WEB-OPERATOR</strong><em>{busy?'PROCESS RUNNING':'INTERNAL NETWORK // NO EGRESS'}</em></div><div className="forge-history" ref={scrollRef}>{history.map((line,index)=><div key={index} className={line.kind}>{line.kind==='command'&&<b>root@web-forge › </b>}{line.text}</div>)}</div><form onSubmit={event=>{event.preventDefault();run()}}><span>root@web-forge</span><b>›</b><input autoFocus disabled={busy} value={input} onChange={event=>setInput(event.target.value)} placeholder="run anything inside the sealed range"/><button disabled={busy}>EXECUTE</button></form></section><aside className="forge-objectives"><div className="forge-brief"><span>SCENARIO CONTRACT</span><h2>{lab.title}</h2><p>{lab.brief}</p><small>STOP CONDITION // ONE CONTROLLED COMPARISON</small></div><div className="forge-step-list"><header><Flag/><span>OPERATION SEQUENCE</span><strong>{done.length}/4</strong></header>{lab.steps.map((step,index)=><button key={step.label} className={done.includes(index)?'done':''} onClick={()=>run(step.command)}><span>{done.includes(index)?<Check/>:`0${index+1}`}</span><div><strong>{step.label}</strong><code>{step.command}</code></div><Play/></button>)}</div><div className="forge-evidence"><header>EVIDENCE LOCKER // {evidence.length}</header>{evidence.map((item,index)=><p key={item}><span>E-{String(index+1).padStart(2,'0')}</span>{item}</p>)}</div><button className="forge-hint" onClick={()=>run('hint')}><Sparkles/> REQUEST GUIDANCE <span>-75 PTS</span></button></aside></main></div>
}
